name: Build native image
on:
  push:
    path:
      - src
      - project.clj
      - reflection.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-graalvm@1.0
      with:
        graalvm-version: '19.2.1'
    - name: Install dependencies
      run: |
        echo "Install dependencies"
        gu install native-image
        curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod a+x lein
    - name: Build uberjar
      run: |
        echo "Build uberjar"
        ./lein uberjar
    - name: Build native image
      run: |
        echo "Build native image"
        native-image \
          -jar target/ye-0.1.0-SNAPSHOT-standalone.jar \
          -H:Name=ye \
          -H:+ReportExceptionStackTraces \
          -J-Dclojure.spec.skip-macros=true \
          -J-Dclojure.compiler.direct-linking=true \
          -H:Log=registerResource: \
          -H:ReflectionConfigurationFiles=reflection.json \
          --verbose \
          --no-fallback \
          --no-server \
          --report-unsupported-elements-at-runtime \
          --initialize-at-build-time \
          --static \
          -J-Xms2g \
          -J-Xmx4g
