name: Build native image
on:
  push:
    paths:
      - src/ye/*.clj
      - project.clj
      - reflection.json
  pull_request:
    paths:
      - src/ye/*.clj
      - project.clj
      - reflection.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: rinx/setup-graalvm-ce@v0.0.1
      with:
        graalvm-version: "19.3.0"
        java-version: "java8"
    - name: Install dependencies
      run: |
        gu install native-image
        curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod a+x lein
        echo "::set-env name=JAVA_HOME::$GRAALVM_HOME"
    - name: Build uberjar
      run: |
        ./lein uberjar
    - name: Build native image
      run: |
        make XMS=4g XMX=6g
