name: Build native image
on:
  push:
    paths:
      - src/ye/*.clj
      - project.clj
      - reflection.json
  pull_request:
    paths:
      - src/ye/*.clj
      - project.clj
      - reflection.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-graalvm@1.0
      with:
        graalvm-version: '19.3.0.java11'
    - name: Install dependencies
      run: |
        gu install native-image
        curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod a+x lein
    - name: Build uberjar
      run: |
        ./lein uberjar
    - name: Build native image
      run: |
        make XMS=4g XMX=6g
